print("Hello, World")
print("Hello, World")
print("Hello, World")
print("Hello, World")
print("it goes to secondary")
print("it goes to secondary")
print("it goes to secondary")
print("it goes to secondary")
print("it goes to third")
print("it goes to third")